-- Stabilize LIFF checkout by making order creation idempotent.
-- A checkout_request_id is generated by the client and reused when a request is retried.

alter table public.orders
  add column if not exists checkout_request_id uuid;

create unique index if not exists orders_customer_checkout_request_uidx
  on public.orders(customer_id, checkout_request_id)
  where checkout_request_id is not null;

create or replace function public.place_liff_order_v3(
  p_customer_id uuid,
  p_items jsonb,
  p_fulfillment_method text,
  p_payment_method public.payment_method,
  p_recipient_name text,
  p_recipient_phone text,
  p_shipping_address text default null,
  p_pickup_at timestamptz default null,
  p_customer_note text default null,
  p_coupon_code text default null,
  p_address_id uuid default null,
  p_delivery_latitude numeric default null,
  p_delivery_longitude numeric default null,
  p_delivery_location_source text default null,
  p_save_address boolean default false,
  p_address_label text default 'บ้าน',
  p_checkout_request_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_lock_key bigint;
begin
  if p_checkout_request_id is null then
    raise exception 'CHECKOUT_REQUEST_ID_REQUIRED';
  end if;

  -- Serialize retries for the same customer/request pair before checking/creating.
  v_lock_key := pg_catalog.hashtextextended(
    p_customer_id::text || ':' || p_checkout_request_id::text,
    0
  );
  perform pg_catalog.pg_advisory_xact_lock(v_lock_key);

  select id
  into v_order_id
  from public.orders
  where customer_id = p_customer_id
    and checkout_request_id = p_checkout_request_id
  limit 1;

  if found then
    return v_order_id;
  end if;

  v_order_id := public.place_liff_order_v2(
    p_customer_id,
    p_items,
    p_fulfillment_method,
    p_payment_method,
    p_recipient_name,
    p_recipient_phone,
    p_shipping_address,
    p_pickup_at,
    p_customer_note,
    p_coupon_code,
    p_address_id,
    p_delivery_latitude,
    p_delivery_longitude,
    p_delivery_location_source,
    p_save_address,
    p_address_label
  );

  update public.orders
  set checkout_request_id = p_checkout_request_id
  where id = v_order_id;

  return v_order_id;
end;
$$;

revoke all on function public.place_liff_order_v3(
  uuid, jsonb, text, public.payment_method, text, text, text, timestamptz,
  text, text, uuid, numeric, numeric, text, boolean, text, uuid
) from public, anon, authenticated;

grant execute on function public.place_liff_order_v3(
  uuid, jsonb, text, public.payment_method, text, text, text, timestamptz,
  text, text, uuid, numeric, numeric, text, boolean, text, uuid
) to service_role;
